#!/bin/bash
#dep : cargo de
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh



echo "ALACRITTY :"
if [[ "$DE" == "none" ]] ; then
  echo ">> no desktop environment, shouldn't be called"
  exit(1)
fi

if [[ "$CONFIG_ONLY" ]] ; then
  echo ">> config only"
elif which alacritty >/dev/null ; then
  echo ">> already installed"
else 
  echo ">> installing..."
  cargo install alacritty
fi


case "$DE" in
  gnome)
    gsettings set org.gnome.desktop.default-applications.terminal exec 'alacritty'
    gsettings set org.gnome.desktop.default-applications.terminal exec-arg ''
    ;;&
  *)
    install_config alacritty.desktop .local/share/applications/alacritty.desktop
    mkdir -p .local/share/icons/
    wget https://github.com/alacritty/alacritty/raw/master/extra/logo/alacritty-term.svg -O ~/.local/share/icons/alacritty.svg
    ;;
esac

wget https://raw.githubusercontent.com/alacritty/alacritty/master/extra/alacritty.info
tic -xe alacritty,alacritty-direct alacritty.info
rm alacritty.info

install_config alacritty.toml .config/alacritty/alacritty.toml
