#!/bin/bash
#dep : cargo de
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh



echo "ALACRITTY :"
if [[ "$CONFIG_ONLY" ]] ; then
  echo ">> config only" ; [[ -z "$DRY_RUN" ]] || exit 0
elif command -v alacritty >/dev/null ; then
  echo ">> already installed" ; [[ -z "$DRY_RUN" ]] || exit 0
else 
  echo ">> installing..." ; [[ -z "$DRY_RUN" ]] || exit 0
  cargo install alacritty
fi


case "$DE" in
  gnome)
    gsettings set org.gnome.desktop.default-applications.terminal exec 'alacritty'
    gsettings set org.gnome.desktop.default-applications.terminal exec-arg ''
    ;;&
  *) #FOR ALL
    install_config alacritty.desktop .local/share/applications/alacritty.desktop
    mkdir -p .local/share/icons/
    wget https://github.com/alacritty/alacritty/raw/master/extra/logo/alacritty-term.svg -O ~/.local/share/icons/alacritty.svg
    ;;
esac

wget https://raw.githubusercontent.com/alacritty/alacritty/master/extra/alacritty.info
tic -xe alacritty,alacritty-direct alacritty.info
rm alacritty.info

install_config alacritty.toml .config/alacritty/alacritty.toml
