#!/bin/bash
#dep : 
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

echo "TEMPLATE :"
if [[ "$CONFIG_ONLY" ]] ; then
  echo ">> config only" ; [[ -z "$DRY_RUN" ]] || exit 0
elif command -v >/dev/null ; then
  echo ">> already installed" ; [[ -z "$DRY_RUN" ]] || exit 0
else 
  echo ">> installing... " ; [[ -z "$DRY_RUN" ]] || exit 0
fi


install_config test1.config .config/test1.config
