#!/bin/bash
# dep : 
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

echo "TEMPLATE :"
if [[ "$CONFIG_ONLY" ]] ; then
  echo ">> config only" ; [[ "$DRY_RUN" ]] && exit 0
elif which >/dev/null ; then
  echo ">> already installed" ; [[ "$DRY_RUN" ]] && exit 0
else 
  echo ">> installing... " ; [[ "$DRY_RUN" ]] && exit 0
fi


install_config test1.config .config/test1.config
