#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

echo "CARGO :"
if [[ "$CONFIG_ONLY" ]] ; then
  echo ">> config only" ; [[ "$DRY_RUN" ]] && exit 0
elif command -v cargo >/dev/null ; then
  echo ">> already installed" ; [[ "$DRY_RUN" ]] && exit 0
else 
  echo ">> installing..." ; [[ "$DRY_RUN" ]] && exit 0
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi

install_config config.toml .cargo/config.toml
