alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ..='cd ..'
alias ll='ls -alsFh'
alias la='ls -A'
alias l='ls -CF'
alias top='top -d 1'
alias go='xdg-open'
alias ip='ip -c=auto'
alias ipa='ip -c=auto -br a'
alias tectonic='tectonic -X'
alias dc='docker compose'
alias dcu='docker compose up -d'
alias dcr='docker compose restart'
alias dcd='docker compose down'
alias dcrun='docker compose run --rm --no-deps'
alias vc='vcs -nsw6 custom --args'
alias lgl='lazygit log'
