#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh


#if [[ ! "$CONFIG_ONLY" ]] && [[ "$INSTALL_WITH_SUDO" ]]; then
#  repo="dandavison/delta"
#  latest=$(curl -s "https://api.github.com/repos/${repo}/releases/latest"|jq -r '.tag_name')
#  wget -O/tmp/git-delta.deb "https://github.com/$repo/releases/download/${latest}/git-delta-musl_${latest}_amd64.deb"
#  sudo dpkg -i /tmp/git-delta.deb
#fi

echo "GIT :"
if [[ "$CONFIG_ONLY" ]] ; then
  echo ">> config only"
elif which git >/dev/null ; then
  echo ">> already installed"
else 
  echo ">> installing git"
  if [[ "$INSTALL_WITH_SUDO" ]]; then
    sudo apt install git
  else
    echo ">> need sudo..."
  fi
fi

install_config gitconfig .gitconfig
