#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh


#if [[ ! "$CONFIG_ONLY" ]] && [[ "$INSTALL_WITH_SUDO" ]]; then
#  repo="dandavison/delta"
#  latest=$(curl -s "https://api.github.com/repos/${repo}/releases/latest"|jq -r '.tag_name')
#  wget -O/tmp/git-delta.deb "https://github.com/$repo/releases/download/${latest}/git-delta-musl_${latest}_amd64.deb"
#  sudo dpkg -i /tmp/git-delta.deb
#fi

echo "GIT :"
if [[ "$CONFIG_ONLY" ]] ; then
  echo ">> config only" ; [[ "$DRY_RUN" ]] && exit 0
elif which git >/dev/null ; then
  echo ">> already installed" ; [[ "$DRY_RUN" ]] && exit 0
else 
  echo ">> installing... (SUDO)" ; [[ "$DRY_RUN" ]] && exit 0
  sudo apt-get install -y git
fi

install_config gitconfig .gitconfig
