#!/bin/bash
#dep : zsh
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

echo "STARSHIP :"
if [[ "$CONFIG_ONLY" ]] ; then
  echo ">> config only" ; [[ -z "$DRY_RUN" ]] || exit 0
elif command -v starship>/dev/null ; then
  echo ">> already installed" ; [[ -z "$DRY_RUN" ]] || exit 0
else 
  echo ">> installing..." ; [[ -z "$DRY_RUN" ]] || exit 0
  curl -sS https://starship.rs/install.sh | sh
fi


zsh_config_dir='.zsh'

mkdir -p "$HOME/${zsh_config_dir}/completion"

install_config starship.toml .config/starship.toml
