#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

echo "HELIX :"
if [[ "$CONFIG_ONLY" ]] ; then
  echo ">> config only" ; [[ "$DRY_RUN" ]] && exit 0
elif command -v hx >/dev/null ; then
  echo ">> already installed" ; [[ "$DRY_RUN" ]] && exit 0
else 
  echo ">> installing... (SUDO)" ; [[ "$DRY_RUN" ]] && exit 0
  sudo add-apt-repository ppa:maveonair/helix-editor
  sudo apt-get install -y helix
fi

install_config config.toml .config/helix/config.toml
install_config languages.toml .config/helix/languages.toml
