#!/bin/bash
#dep : de
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

echo "ROFI :"
if [[ "$CONFIG_ONLY" ]] ; then
  echo ">> config only" ; [[ -z "$DRY_RUN" ]] || exit 0
elif command -v rofi>/dev/null ; then
  echo ">> already installed" ; [[ -z "$DRY_RUN" ]] || exit 0
else 
  echo ">> installing... (SUDO)" ; [[ -z "$DRY_RUN" ]] || exit 0
  sudo apt-get install -y rofi
fi

case "$DE" in
  gnome)
    add_gnome_shortcut "Lancer Rofi" "rofi -show run" "<Super>x"
    ;;&
  *) #FOR ALL
    ;;
esac

install_config config.rasi .config/rofi/config.rasi
