#!/bin/bash
#dep : pipx
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

echo "PYLSP :"

if [[ "$CONFIG_ONLY" ]] ; then
  echo ">> config only"  ; [[ -z "$DRY_RUN" ]] || exit 0
elif command -v pylsp>/dev/null ; then
  echo ">> already installed" ; [[ -z "$DRY_RUN" ]] || exit 0
else 
  echo ">> installing... (SUDO)" ; [[ -z "$DRY_RUN" ]] || exit 0
  pipx install python-lsp-server
  pipx inject python-lsp-server python-lsp-ruff
  ln -sf ~/.local/share/pipx/venvs/python-lsp-server/bin/ruff ~/.local/bin/ruff
fi

install_config ruff.toml .config/ruff/ruff.toml
