#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

echo "LAZYGIT :"

install_config config.yml .config/lazygit/config.yml


if [[ "$CONFIG_ONLY" ]] ; then
  echo ">> config only"
elif which lazygit >/dev/null ; then
  echo ">> already installed"
else 
  echo ">> installing "
  LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | \grep -Po '"tag_name": *"v\K[^"]*')
  curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/download/v${LAZYGIT_VERSION}/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
  tar xf lazygit.tar.gz lazygit
  if [[ "$INSTALL_WITH_SUDO" ]]; then
    sudo install lazygit -D -t /usr/local/bin/
  else
    sudo install lazygit -D -t $USER/.local/bin/
  fi
  rm lazygit
  rm lazygit.tar.gz
fi
