#!/bin/bash
#dep : 
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

echo "PIPX :"
if [[ "$CONFIG_ONLY" ]] ; then
  echo ">> config only" ; [[ -z "$DRY_RUN" ]] || exit 0
elif command -v pipx>/dev/null ; then
  echo ">> already installed" ; [[ -z "$DRY_RUN" ]] || exit 0
else 
  echo ">> installing... " ; [[ -z "$DRY_RUN" ]] || exit 0
  sudo apt-get install -y pipx
  pipx ensurepath
fi

