#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh


echo "ZELLIJ :"
if [[ "$CONFIG_ONLY" ]] ; then
  echo ">> config only"
elif which zellij >/dev/null ; then
  echo ">> already installed"
else 
  echo ">> installing zellij"
  if ! which cargo >/dev/null ; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  fi
  cargo install --locked zellij
  add_gnome_shortcut "Launch Zellij with layout" "$HOME/.config/zellij/launch_layout.bash" "<Ctrl><Alt>y" true
fi

add_gnome_shortcut "Launch Zellij with layout" "$HOME/.config/zellij/launch_layout.bash" "<Ctrl><Alt>y" true

install_config launch_layout.bash .config/zellij/launch_layout.bash
install_config layouts.d .config/zellij/layouts.d
install_config config.kdl .config/zellij/config.kdl
