#!/bin/bash
#dep : cargo
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh


echo "ZELLIJ :"
if [[ "$CONFIG_ONLY" ]] ; then
  echo ">> config only" ; [[ ! "$DRY_RUN" ]] && exit 0
elif which zellij >/dev/null ; then
  echo ">> already installed" ; [[ ! "$DRY_RUN" ]] && exit 0
else 
  echo ">> installing..." ; [[ ! "$DRY_RUN" ]] && exit 0
  cargo install --locked zellij
fi

add_gnome_shortcut "Launch Zellij with layout" "$HOME/.config/zellij/launch_layout.bash" "<Ctrl><Alt>y" true

install_config launch_layout.bash .config/zellij/launch_layout.bash
install_config layouts.d .config/zellij/layouts.d
install_config config.kdl .config/zellij/config.kdl

zsh_config_dir='.zsh'
zellij_completion_file="${zsh_config_dir}/completion/_zellij"
if which zsh >/dev/null && [[ ! -r "${zellij_completion_file}" ]] ; then
  # TODO verif don't need mkdir
  zellij setup --generate-completion zsh >"${HOME}/${zellij_completion_file}"
fi
