#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

echo "ZSH :"

zsh_config_dir='.zsh'

mkdir -p "$HOME/${zsh_config_dir}/completion"

#TODO Try isntall config after

install_config zshrc .zshrc
install_config zshenv .zshenv
install_config cfg "${zsh_config_dir}/cfg"


if [[ "$CONFIG_ONLY" ]] ; then
  echo ">> config only"
elif which zsh>/dev/null ; then
  echo ">> already installed"
else 
  echo ">> installing... (SUDO)"
  sudo apt-get install -y zsh zsh-syntax-highlighting
fi


