#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

echo "ZSH :"

zsh_config_dir='.zsh'

mkdir -p "$HOME/${zsh_config_dir}/completion"

#TODO Try isntall config after


if [[ "$CONFIG_ONLY" ]] ; then
  echo ">> config only" ; [[ -z "$DRY_RUN" ]] || exit 0
elif command -v zsh>/dev/null ; then
  echo ">> already installed" ; [[ -z "$DRY_RUN" ]] || exit 0
else 
  echo ">> installing... (SUDO)" ; [[ -z "$DRY_RUN" ]] || exit 0
  sudo apt-get install -y zsh zsh-syntax-highlighting
fi


install_config zshrc .zshrc
install_config zshenv .zshenv
install_config cfg "${zsh_config_dir}/cfg"

