#!/bin/bash
#dep : cargo
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

echo "TOOLS :"
if [[ ! "$CONFIG_ONLY" ]] ; then
  if ! command -v fd >/dev/null ; then (
    echo "installing fd_find" ; [[ -z "$DRY_RUN" ]] || exit 0
    cargo install fd-find
  ) fi

  if ! command -v rg >/dev/null ; then (
    echo "installing ripgrep" ; [[ -z "$DRY_RUN" ]] || exit 0
    cargo install ripgrep
  ) fi
  
  if ! command -v bat >/dev/null ; then (
    echo "installing bat" ; [[ -z "$DRY_RUN" ]] || exit 0
    cargo install bat
  ) fi

  if ! command -v sd >/dev/null ; then (
    echo "installing sd" ; [[ -z "$DRY_RUN" ]] || exit 0
    cargo install sd
  ) fi

  if ! command -v exa >/dev/null ; then (
    echo "installing exa" ; [[ -z "$DRY_RUN" ]] || exit 0
    cargo install exa
  ) fi
  
  if ! command -v jaq >/dev/null ; then (
    echo "installing jaq" ; [[ -z "$DRY_RUN" ]] || exit 0
    cargo install jaq
  ) fi

  if ! command -v dua >/dev/null ; then (
    echo "installing dua" ; [[ -z "$DRY_RUN" ]] || exit 0
    cargo install dua-cli
  ) fi

  if ! command -v bandwhich >/dev/null ; then (
    echo "installing bandwhich" ; [[ -z "$DRY_RUN" ]] || exit 0
    cargo install bandwhich
    #making it visible from sudoers
    sudo ln -s ~/.cargo/bin/bandwhich /usr/local/bin/bandwhich 
  ) fi


  if ! command -v hyperfine >/dev/null ; then (
    echo "installing hyperfine" ; [[ -z "$DRY_RUN" ]] || exit 0
    cargo install hyperfine
  ) fi


  if ! command -v pastel >/dev/null ; then (
    echo "installing pastel" ; [[ -z "$DRY_RUN" ]] || exit 0
    cargo install pastel
  ) fi


  if ! command -v xsv >/dev/null ; then (
    echo "installing xsv" ; [[ -z "$DRY_RUN" ]] || exit 0
    cargo install xsv
  ) fi
fi
